apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: efk
data:
  additional.conf: |
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**nginx-ingress**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**cattle**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kibana**.log>
      @type null
    </match>
    
    <filter **>
      @type grep
      <exclude>
        key log
        pattern ^\r*\n$
      </exclude>
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      remove_keys $.stream, $.docker, $.kubernetes.container_image, $.kubernetes.container_image, $.kubernetes.container_image_id, $.kubernetes.labels, $.kubernetes.master_url, $.kubernetes.namespace_id, $.kubernetes.namespace_labels, $.kubernetes.pod_id
    </filter>

    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      replace_invalid_sequence true
      reserve_time true
      <parse>
        @type multi_format
        <pattern>
          format json
          json_parser json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>